### ISSUE TITLE
Can't start newest version on Windows 10 x64

### ISSUE THREAD

**Issue by rafx85** [dawidm/cryptonose2#3]
Hi,

I wanted to test this program, but I can't start it, when I click the icon nothing happens. Any help with that? What could I check in this case?

Regards,
Rafal

**Comment by dawidm** [comment]
Hello, Do I understand well that what you described is happening after installation? I've seen similar issue on Windows 7. Weird thing was that uninstalling and installing in different location fixed it. Could you try to do this? 
Cheers

**Comment by rafx85** [comment]
Yes, it happens after installation, earlier version works well, but newest one not. I will try to install in a different location. Thank you.

**Comment by dawidm** [comment]
I've checked on another Windows machine and I get same behavior as you and reinstalling doesn't help. I will be working on it. Thanks for the report!

**Comment by dawidm** [comment]
@rafx85 It seems that I've found a workaround for this. I've re-uploaded v2.13.0 windows installer with the fix. Could you let me know whether it works for you now?

**Comment by rafx85** [comment]
Now it works. Thank you very much.
