### ISSUE TITLE
Alerts are not Audible if Changed from the Default Sounds [Fedora 33]

### ISSUE THREAD

**Issue by bongochong** [dawidm/cryptonose2#4]
First, let me say that this is an extremely useful utility for monitoring price changes on crypto exchanges. It is absolutely indispensable on GNU/Linux (where the only competitor is Donut, which has been a defunct project for quite some time now). That being said, I have noticed one bug, and only one bug. It is this:

If one attempts to use other WAV files for the notification sounds, audio notifications cease to work entirely. I have attempted to set a number of different WAV files which play just fine in a variety of media players, yet, when set as notification sounds in Cryptonose, they are inaudible. It should be noted that the default sounds play back just fine.

Many thanks for this otherwise stellar program, and please let me know if there's anything I can do to help you isolate the source of this issue on my platform.

**Comment by dawidm** [comment]
Thanks for the positive feedback and the bug report :) I will check this as soon as possible on Linux Mint and Windows.

**Comment by dawidm** [comment]
Okay, I must admit I probably haven't tested it before, because looking at the current code - it's not possible for custom sound files to work ;) But it's easy to fix and it will be included in the next release, probably at the end of the week.

**Comment by bongochong** [comment]
Whoah! Quick work. Bushels of thanks.
