### ISSUE TITLE
Soft made as appimage for wide use - any plan?

### ISSUE THREAD

**Issue by docop** [dawidm/cryptonose2#8]
Hi  so your soft look quite geat with the alert function. Nice to see this. Also, i wonder if you have plan to release this as appimage ?  It's quite wide support on any kind of linux and all lib/extra stuff are all included in within 1 file.
Thanks in advance

**Comment by dawidm** [comment]
Hello, I'm glad you find Cryptonose useful. Turns out it's quite easy to create an AppImage from a deb package. I've created it for the newest version: https://github.com/dawidm/cryptonose2/releases/download/v2.22.0/cryptonose-linux-x86_64.AppImage Let me know if it works for you :)

**Comment by docop** [comment]
Hi  just read your reply. Great to see that. It will be super usefull !  i tried over a centos based system and it look it just don't run.  have you made it for ubuntu or other ? Thanks

**Comment by docop** [comment]
Tried over ubuntu 21.1 and it give : inconsistency detected by ld.so: dl-call-libc-early-init.c : 37: _dl_call_libc_early_init: Assertion 'sym != Null' failed!
 happy new year.

**Comment by dawidm** [comment]
Hi, happy new year :) Thanks for checking this. I've been testing it on Ubuntu 20.04 and it worked fine, but I've tried on Arch Linux and got the same error. I've corrected the AppImage configuration and it should work well now. Here's an AppImage for the newest version https://github.com/dawidm/cryptonose2/releases/download/v2.22.4/cryptonose-linux-x86_64.AppImage

**Comment by docop** [comment]
Hi tested on a ubuntu 21.10 full update. do work fine !
many thanks
